spring.datasource.url=jdbc:sqlserver://mysql.railway.internal:3306;databaseName=railway;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=vTdaPtlFkoXftXPZmCtoYyIVBIOuXnSC

spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update